---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/wp-content/
    - /bin/cp -R /home/linkroob/repos/linkroob/themes $DEPLOYPATH
    - /bin/cp -R /home/linkroob/repos/linkroob/plugins $DEPLOYPATH